language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '12'
  - '10'
  - '8'
script:
  - npx run-s test:prod build
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
